# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(max_length=500)),
                ('Instructor', models.CharField(max_length=100)),
                ('Duration', models.CharField(choices=[('8', '8'), ('12', '12')], default='8', max_length=2)),
                ('CourseArt', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
