# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_remove_course_courseart'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseArt',
            field=models.FileField(default='2', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.CharField(choices=[('8', '8'), ('2', '2')], default='8', max_length=1),
        ),
    ]
