# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_auto_20170302_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseArt',
            field=models.FileField(upload_to=b''),
        ),
    ]
