# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_auto_20170302_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseArt',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
